# Generated by Django 4.2.20 on 2025-04-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
