# Generated by Django 4.2.20 on 2025-04-16 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reading_content', models.JSONField(blank=True, null=True)),
                ('listening_content', models.JSONField(blank=True, null=True)),
                ('writing_content', models.JSONField(blank=True, null=True)),
                ('reading_responses', models.JSONField(blank=True, null=True)),
                ('listening_responses', models.JSONField(blank=True, null=True)),
                ('writing_responses', models.JSONField(blank=True, null=True)),
                ('reading_score', models.FloatField(blank=True, null=True)),
                ('listening_score', models.FloatField(blank=True, null=True)),
                ('writing_score', models.FloatField(blank=True, null=True)),
                ('speaking_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
