# Generated by Django 4.2.20 on 2025-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts_mock', '0002_mocktest_areas_for_improvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='audio_paths',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
